language: python
python:
 - 2.6
 - 2.7
 - 3.2
 - 3.3
 - pypy
install:
 - python setup.py install
 - pip install coveralls
 - mkdir local_cache
script:
 - SC2BNET_CACHE_DIR=local_cache coverage run tests.py
after_success:
 - coveralls
branches:
  only:
    - master
notifications:
  irc: "chat.freenode.net#sc2reader"
